version: 0.2

phases:
  build:
    commands:
      - echo "Building Lambda function"
      - pip install -r requirements.txt -t .
      - zip -r lambda-code.zip .
artifacts:
  files:
    - lambda-code.zip
